## Системы линейных уравнений. Часть 2

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$


   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

$$detA=\begin{vmatrix}
1 & -2 \\ 
3 & -4 \\ 
\end{vmatrix} = -2$$

$$detA_{1}=\begin{vmatrix}
1 & -2 \\ 
7 & -4 \\ 
\end{vmatrix} = -10$$

$$detA_{2}=\begin{vmatrix}
1 & 1 \\ 
3 & 7 \\ 
\end{vmatrix} = -4$$

$$x_{1} = \frac{detA_{1}}{detA} = \frac{-2}{-10}=0.2,$$

$$x_{2} = \frac{detA_{2}}{detA} = \frac{-2}{-4}=0.5,$$

   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$


$$detA=\begin{vmatrix}
2 & -1 & 5\\ 
1 & 1 & -3\\ 
2 & 4 & 1
\end{vmatrix}=
2\begin{vmatrix}
1 & -3\\ 
4 & 1 
\end{vmatrix}+
\begin{vmatrix}
1 & -3\\ 
2 & 1 
\end{vmatrix}+5
\begin{vmatrix}
1 & 1 \\ 
2 & 4
\end{vmatrix}=43\neq 0$$

следовательно, система совместна.

Найдем определители $detA_{1}$, $detA_{2}$, $detA_{3}$:

$$detA_{1}=\begin{vmatrix}
10 & -1 & 5\\ 
-2 & 1 & -3\\ 
1 & 4 & 1
\end{vmatrix}=
10\begin{vmatrix}
1 & -3\\ 
4 & 1 
\end{vmatrix}+
\begin{vmatrix}
-2 & -3\\ 
1 & 1 
\end{vmatrix}+
5\begin{vmatrix}
-2 & 1 \\ 
1 & 4
\end{vmatrix}=86$$

$$detA_{2}=\begin{vmatrix}
2 & 10 & 5\\ 
1 & -2 & -3\\ 
2 & 1 & 1
\end{vmatrix}=
2\begin{vmatrix}
-2 & -3\\ 
1 & 1 
\end{vmatrix}-
10\begin{vmatrix}
1 & -3\\ 
2 & 1 
\end{vmatrix}+5
\begin{vmatrix}
1 & -2 \\ 
2 & 1
\end{vmatrix}=-43$$

$$detA_{3}=\begin{vmatrix}
2 & -1 & 10\\ 
1 & 1 & -2\\ 
2 & 4 & 1
\end{vmatrix}=
2\begin{vmatrix}
1 & -2\\ 
4 & 1 
\end{vmatrix}+
\begin{vmatrix}
1 & -2\\ 
2 & 1 
\end{vmatrix}+
10\begin{vmatrix}
1 & 1 \\ 
2 & 4
\end{vmatrix}=43$$

Найдем решение по формулам Крамера:

$$x_{1} = \frac{detA_{1}}{detA} = \frac{86}{43}=2,$$

$$x_{2} = \frac{detA_{2}}{detA} = \frac{-43}{43}=-1,$$

$$x_{3} = \frac{detA_{3}}{detA} = \frac{43}{43}=1$$

Прозведем проверку с помощью python

In [3]:
import numpy as np
a = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ 2 -1  5]
 [ 1  1 -3]
 [ 2  4  1]]
Определитель:
43


In [10]:
a1 = np.array([[10, -1, 5], [-2, 1, -3], [1, 4, 1]])
print(f'Матрица:\n{a1}')
print(f'Определитель:\n{np.linalg.det(a1):.0f}')

Матрица:
[[10 -1  5]
 [-2  1 -3]
 [ 1  4  1]]
Определитель:
86


In [11]:
a2 = np.array([[2, 10, 5], [1, -2, -3], [2, 1, 1]])
print(f'Матрица:\n{a2}')
print(f'Определитель:\n{np.linalg.det(a2):.0f}')

Матрица:
[[ 2 10  5]
 [ 1 -2 -3]
 [ 2  1  1]]
Определитель:
-43


In [12]:
a3 = np.array([[2, -1, 10], [1, 1, -2], [2, 4, 1]])
print(f'Матрица:\n{a3}')
print(f'Определитель:\n{np.linalg.det(a3):.0f}')

Матрица:
[[ 2 -1 10]
 [ 1  1 -2]
 [ 2  4  1]]
Определитель:
43


__2.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

a) Начнем прямой ход метода Гаусса. Для этого домножим первую строку на $2$ и вычтем ее из второго уравнения. При этом запишем в матрицу $L$ на место элемента $l_{21}$ значение $2$. Затем нам нужно вычесть из третьего уравнения первое, домноженное на $3$. Значит, в матрицу $L$ запишем $l_{31}=3$. 

Матрица коэффициентов будет иметь вид

$$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 14 & 4 \\ 
0 & 20 & 18
\end{pmatrix}$$

а матрица $L$ —

$$\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & l_{32} & 1
\end{pmatrix}$$

Далее умножим вторую строку на $10/7$ и вычтем ее из третьей. При этом в матрицу $L$ на место $l_{32}$ запишем $10/7$.

В итоге получим

$$U=\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 14 & 4 \\ 
0 & 0 & -16.2
\end{pmatrix}$$

$$L=\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 10/7 & 1
\end{pmatrix}$$

   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

__4.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

Произведем разложение на $LL^{T}$:

$$l_{11}=\sqrt{a_{11}}=9,$$
$$l_{21}=\frac{a_{21}}{l_{11}}=-5,$$
$$l_{31}=\frac{a_{31}}{l_{11}}=3,$$

$$l_{22}=\sqrt{a_{22}-u_{21}^{2}}=\sqrt{50 - 25}=5,$$
$$l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right)=0.2\left ( 15 - (-5)\cdot 5 \right )=2,$$

$$l_{33}=\sqrt{a_{33}-l_{31}^{2}-l_{32}^{2}}=\sqrt{38-25-4}=3.$$


Получили матрицу 

$$L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}, 
\; \; 
L^{T} = \begin{pmatrix}
9 & -5 & 5 \\
0 & 5 & 2\\ 
0 & 0 & 3
\end{pmatrix}.$$

Решим систему $Ly=b:$

$$\begin{cases}
9y_{1}=531, \\
-5y_{1}+5y_{2}=-460, \\
5y_{1}+2y_{2}+3y_{3}=193.
\end{cases}$$

$$y_{1} = 59,$$

$$y_{2}=-82.5,$$

$$y_{3}=21.$$

И решим систему $L^{T}x=y:$

$$\begin{cases}
9x_{1}-5x_{2}+5x_{3}=59, \\
5x_{2}+2x_{3}=-82.5, \\
3x_{3}=21.
\end{cases}$$

$$x_{3}=7,$$

$$x_{2}=-19.3,$$

$$x_{1}=-8.06.$$