# Практическое задание

## Матрицы и матричные операции. Часть 1

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$ - произведение __не посчитать__, т.к. число столбцов первой матрицы не равно числу строк во второй матрице
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$ - произведение __считается__, итоговая матрица будет размером 2х3
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$ - произведение __считается__, итоговая матрица будет размером 8х8
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$- произведение __считается__, итоговая матрица будет размером 4х4

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [101]:
import numpy as np
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(f'Матрицы:\n A:\n{A}\nB:\n{B}')
print(f'Сумма матриц:\n{A + B}')
print(f'Произведение матриц:\n {np.dot(A, B)}')

Матрицы:
 A:
[[ 1 -2]
 [ 3  0]]
B:
[[ 4 -1]
 [ 0  5]]
Сумма матриц:
[[ 5 -3]
 [ 3  5]]
Произведение матриц:
 [[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [67]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print(f'Матрицы:\nA:\n {A}\nB:\n{B}\nC:\n{C}')

Матрицы:
A:
 [[ 1  7]
 [ 3 -6]]
B:
[[ 0  5]
 [ 2 -1]]
C:
[[ 2 -4]
 [ 1  1]]


In [71]:
3*A - 2*B + 4*C

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [102]:
A4 = np.array([[4, 1], [5, -2], [2, 3]])
A4_T = np.transpose(A4)

In [103]:
A4

array([[ 4,  1],
       [ 5, -2],
       [ 2,  3]])

In [104]:
A4_T

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [105]:
np.dot(A4, A4_T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [106]:
np.dot(A4_T, A4)

array([[45,  0],
       [ 0, 14]])

## Матрицы и матричные операции. Часть 2

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$


$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = sinx*sinx-(-cosx)*cosx = sinx^2+cosx^2=1
$$

In [107]:
L = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Матрица:\n{L}')
print(f'Определитель:\n{np.linalg.det(L)}')

Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:
180


In [108]:
F = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{F}')
print(f'Определитель:\n{np.linalg.det(F)}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
0


__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

In [91]:
G = np.array([[-2, 7, -3], [4, -14, 6], [-3, -7, 13]])
print(f'Матрица:\n{G}')
print(f'Определитель:\n{np.linalg.det(G):.0f}')

Матрица:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3  -7  13]]
Определитель:
0


Т.к. определитель равен 0 матрица вырожденная

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [99]:
K = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
r = np.linalg.matrix_rank(K)
print(f'Матрица:\n{K}')
print(f'Ранг матрицы: {r}')

Матрица:
[[1 2 3]
 [1 1 1]
 [2 3 4]]
Ранг матрицы: 2


In [100]:
Z = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
r = np.linalg.matrix_rank(Z)
print(f'Матрица:\n{Z}')
print(f'Ранг матрицы: {r}')

Матрица:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]
Ранг матрицы: 3


Ранг матрицы равен 3 т.к. третья строка получается суммой первой и третьей строк.